language: python
python:
  - "3.6"
sudo: required
services:
  - docker
script:
  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  # build image
  - docker build -t spammon .
  # test image
  - docker run spammon spammon --version
  # push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      # TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
      docker tag spammon xmayeur/spammon
      docker push xmayeur/spammon
    fi