language: python
python:
- '3.6'
sudo: required
services:
- docker
script:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
- docker build -t spammon .
- |-
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    # TAG=$(grep "ENV MYSQL_VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag spammon xmayeur/spammon
    docker push xmayeur/spammon
  fi
addons:
  ssh_known_hosts: home.mayeur.be
before_deploy:
- openssl aes-256-cbc -K $encrypted_af10b53936f5_key -iv $encrypted_af10b53936f5_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o "StrictHostKeyChecking no" -t root@home.mayeur.be -p 2202 /root/spammon.sh
env:
  global:
  - secure: r6FfpTkPRjMeWl4PzakZO/7F6Tk6esQYw0K17kd1VxSnj923uBdSfD0f8SloAZRv09DzVLeyyvacXkQMwKphAWnrU/mWnNX+2TuWUGx1hCzUqdqIjMtNogeI6XoyRDGwZ86WQdbVZ2tvtcpFrN07Jvjd6XKBttKP3MDTtibpCzSIRdL1HPJbnWbFLX4iiY6QtocO0rQScWatJhg31+zfUq+gcPk9NJmmMHXKSToKXr6tL00JIYvJnOuakPJdhBZvJ+eWN25oxcQ8vvuhmQzOstN67L8CzmbROJ2QzLKKMT5oKrElvDC9A7+wVoJIr8M9Cb/UfimLhgshcdWbgkGKVUOaAX9i34PFHGij8OH8L/Pr0tfpaihB4LjyfeAIfnpEP0hrcdySvYeodT7Axd1nfcQrSIQccTgNyAfu4WbhUFWIP29+PZUCSx97u+b8aVJT6EYoUT+uOIK63aRJXrpVb4d4T8sIg1Xl4GAo2VF3+vZrciioRe1ErURMxhbQZO/dAmSXIJLNv+9wy/Us8xWRkHF/W0LWx/GVLhKFIpaqp3CmVMtZjnybDmdE/GZI3nylN64OV9uFh6yQfZP0F2ncoYXKcfGpBArftAMURKGKj94yi6Z4XFRbWkew10KBH5nzhBvBdOkNnA+ZRVzJAxsJjUaUjQHuepsQURfzUMNCyw4=
  - secure: bHGCX98ekDc6Z/GTwLSi9uy9msoi6NXi3HbuOEWtl0FfdxRS4Q/HJlFmrwqcuYSCLyUrBo2DP0tLHD0JtRjsWAgInJq3q3PYE91g2p8ixnGD86RYICa3pNthlC5JEL3rTeL21VESZzo0KjQqFa+yxYrXWKRLdS4Mh4a6lGaOnMtOL7tJa8ldsEgNpZv+0+f1NIaE8HTK8cwXgLOOjoSUrCUz4LFntF6dhUXh7oAM4MTBjIefIG6YT6caG6kpNhFU4ZKLgaxobVC14p6XpgkU/onmU9z77HZi2BR2OOVnv1F/uO0Yp6RWzx+wOCqgaQu7VReotzYhOFUv0/yK7p9dnjN+/ae/RnbTNNNx0q9gGi2fcSH3MGdIOftqoGmkiSfrv1YOGcdsaI3x7xgR0ZoXAvb9HidtJyOVKfdtgjlwSl87jH0wrc70SYvYwgeHwWQurCep3c9IMX9tnSibovp0e56/6yjTmmcRy0f8epIQJMTSG5anv1nuQW8iFP3cAo7wbJAFELWU6mROLLR4FnBKtwPMBjr0mEyTqEtlHzfqtouhVMK8J5Ko+epFHGJVl+a3JdMa8OtLfP/3pp1HCsMs6d/0Hap78ZAP4v1jQSsqqdtc+pCxp+ZfhvTsV5agV5m3wWf/tTaal/6Z9He9QarX2UbvoUX+JLAsRrsXqlgi+aM=